version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "3434:5432"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SPROCKETS_CACHE=/cache
    volumes:
      - ./:/myapp
      - cache:/cache
    ports:
      - "3232:3000"
    depends_on:
      - db
volumes:
  postgres:
  cache:
